sonar.projectKey=helton-godoy_LightlyShaders
sonar.organization=helton-godoy
sonar.projectName=LightlyShaders
sonar.projectVersion=3.0.0

sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.cxx.file.suffixes=.cpp,.h,.cxx,.hpp

sonar.buildString=Build with CMake
sonar.cfamily.build-wrapper-output=bw-output

sonar.exclusions=build/**,build-qt6/**,**/*.so,**/*.frag,**/*.vert,**/*.qrc,**/*.sh

sonar.clangtidy.reportPaths=clang-tidy-report.txt

sonar.cpp.cppcheck.reportPaths=cppcheck-report.xml

sonar.host.url=https://sonarcloud.io
